version: '3'
name: repo

services:
  api:
    container_name: repo-api
    build:
      context: .
      dockerfile: ./apps/api/image/Dockerfile
      target: dev
    restart: always
    env_file:
      - ./apps/api/.env
    ports:
      - 8000:8000
